"""
Messy Lab, step 3: coverage report.

Writes db/coverage.md from the finished database: what was loaded per study, the issues found per
study, and one line for every row of the mess inventory (M01..M75) saying how it is handled.

  flagged by check  a check in pipeline/checks.py finds it in the data and records it in `issue`
                    (resolution 'flagged': kept and marked for the reader)
  fixed by rule     a mapping rule, reference list or pipeline step corrects it in the clean tables
                    (and a check may also record it with resolution 'fixed_by_rule' or 'excluded')

A row counts as covered only if one of these is true. The build stops if any row is uncovered.
Run by pipeline/build.py after the database is assembled.
"""
import csv
import os
import re
import sys
from pathlib import Path

import duckdb
import yaml

ROOT = Path(__file__).resolve().parent.parent
DB_DIR = Path(os.environ.get("MESSY_LAB_DB_DIR", ROOT / "db"))
FINAL = DB_DIR / "messy_lab.duckdb"
OUT = ROOT / "db" / "coverage.md"

# Fixes made by a reference list or a pipeline step rather than a tagged mapping rule or a check.
BUILT_IN = {
    "M02": "reference/compound_alias.csv maps the paper's 'Tam' to 4-hydroxytamoxifen",
    "M05": "reference/compound_alias.csv maps '4-OH-tamoxifen'; S4.yaml records the 'Tam1/Tam2' lines as derived lines",
    "M14": "S5.yaml reads the dose from its own field; the counts-file label is kept as label_as_given",
    "M15": "S4.yaml stores 1 uM as dose_nM = 1000 whichever micro sign was used",
    "M19": "S2.yaml makes every 0 h sample an untreated baseline, so wild-type time courses have controls",
    "M23": "S1.yaml stores '24hr' as exposure_h = 24",
    "M26": "S4.yaml stores 'eight to twelve months' as exposure_type = chronic",
    "M27": "S5.yaml stores '24h' as exposure_h = 24",
    "M30": "source names are never used for identity; cell lines come from reference/cell_line_alias.csv",
    "M34": "reference/cell_line.csv gives each lab's resistant lines their own IDs and parents",
    "M37": "reference/cell_line.csv records the source bank (ATCC, DSMZ) for each base line",
    "M38": "every mapping file sets hormone_deprived and culture_medium from the protocols",
    "M39": "S2.yaml records the paper's medium and timing and notes GEO's differing version",
    "M54": "sample.lab_sample_code keeps each lab's own ID; the GSM ID is the key",
    "M56": "values.py keeps S2's log2 values as they are",
    "M58": "loaders.py keeps S4's raw counts only; values.py recomputes CPM without the patient samples",
    "M60": "values.py records value_type per study; the data dictionary's first rule is to compare within a study",
    "M62": "genes.py maps S2's RefSeq IDs and parses symbols from the free-text description",
    "M64": "genes.py maps S4 on Ensembl ID; the paper's Ensembl v80 is recorded in the study table",
    "M68": "genes.py joins every study on HGNC ID, raising genes comparable across all five",
    "M69": "loaders.py has one loader per file layout, all writing the same staging tables",
    "M72": "study.notes for S5 records the unresolved read length",
    "M73": "reference/study.yaml records the institution from the paper",
    "M74": "reference/study.yaml records authors from the paper",
    "M75": "the study table stores both the GEO title and the paper title",
}


def mapping_tags():
    tags = {}
    for f in sorted((ROOT / "pipeline" / "mappings").glob("S*.yaml")):
        spec = yaml.safe_load(open(f))
        blocks = list(spec.get("rules") or []) + list((spec.get("samples") or {}).values())
        for b in blocks:
            if b.get("inventory"):
                tags.setdefault(b["inventory"], []).append(f"{f.name}: {b['name']}")
    return tags


def main():
    con = duckdb.connect(str(FINAL), read_only=True)
    inv = list(csv.DictReader(open(ROOT / "mess_inventory" / "mess_inventory.csv")))
    tags = mapping_tags()
    issues = con.execute("""select inventory_id, resolution, check_name, count(*) n from issue
                            where inventory_id is not null group by all""").fetchall()
    by_inv = {}
    for iid, res, chk, n in issues:
        by_inv.setdefault(iid, []).append((res, chk, n))

    L = ["# Messy Lab · Coverage report", "",
         "Generated by `pipeline/coverage.py` from `db/messy_lab.duckdb` on every build. It shows what was loaded, "
         "what the checks found, and how each of the 75 problems in the mess inventory is handled.", ""]

    L += ["## Loaded per study", "",
          "| Study | GEO | Samples | Treatment rows | Genes with values | Expression values | Gene rows matched / total |",
          "|---|---|---|---|---|---|---|"]
    for r in con.execute("""
        select st.study_id, st.geo_accession,
               (select count(*) from sample s where s.study_id = st.study_id),
               (select count(*) from sample_treatment t join sample s using(sample_id) where s.study_id = st.study_id),
               (select count(*) from feature_map f where f.study_id = st.study_id and f.chosen_for_gene),
               (select count(*) from measurement m join sample s using(sample_id) where s.study_id = st.study_id),
               (select count(*) filter (where map_status='mapped') from feature_map f where f.study_id = st.study_id),
               (select count(*) from feature_map f where f.study_id = st.study_id)
        from study st order by 1""").fetchall():
        L.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]:,} | {r[5]:,} | {r[6]:,} / {r[7]:,} |")
    tot = con.execute("select (select count(*) from sample), (select count(*) from measurement)").fetchone()
    common = con.execute("""select count(*) from (select hgnc_id from feature_map where chosen_for_gene
                            group by 1 having count(distinct study_id) = 5)""").fetchone()[0]
    L += ["", f"Total: {tot[0]} samples, {tot[1]:,} expression values. Genes measured in all five studies: {common:,}.", ""]

    L += ["## Issues per study", "",
          "| Study | Breaks | Misleads | Minor | Fixed by rule | Flagged | Excluded | Total |", "|---|---|---|---|---|---|---|---|"]
    for r in con.execute("""select coalesce(study_id,'all'),
                               count(*) filter (where impact='breaks'), count(*) filter (where impact='misleads'),
                               count(*) filter (where impact='minor'), count(*) filter (where resolution='fixed_by_rule'),
                               count(*) filter (where resolution='flagged'), count(*) filter (where resolution='excluded'), count(*)
                            from issue group by 1 order by 1""").fetchall():
        L.append("| " + " | ".join(str(x) for x in r) + " |")
    L += ["", "Counts are issue rows. One problem can touch many samples, e.g. an unstated dose on 49 treatment rows.", ""]

    rows, uncovered, counts = [], [], {"flagged by check": 0, "fixed by rule": 0}
    for r in inv:
        iid = r["id"]
        found = by_inv.get(iid, [])
        flagged = [(c, n) for res, c, n in found if res == "flagged"]
        fixed_checks = [(c, n) for res, c, n in found if res in ("fixed_by_rule", "excluded")]
        how = []
        if flagged:
            status = "flagged by check"
            how.append("; ".join(f"`{c}` ({n})" for c, n in flagged))
        elif fixed_checks or tags.get(iid) or iid in BUILT_IN:
            status = "fixed by rule"
        else:
            status = None
        if fixed_checks:
            how.append("recorded by " + "; ".join(f"`{c}` ({n})" for c, n in fixed_checks))
        if tags.get(iid):
            how.append("; ".join(tags[iid][:2]) + (f" (+{len(tags[iid]) - 2} more)" if len(tags[iid]) > 2 else ""))
        if iid in BUILT_IN:
            how.append(BUILT_IN[iid])
        if status is None:
            uncovered.append(iid)
            status = "NOT COVERED"
        else:
            counts[status] += 1
        what = re.sub(r"\s+", " ", r["what_they_wrote"]).replace("|", "/")
        rows.append(f"| {iid} | {r['study']} | {r['impact']} | {what[:90]}{'…' if len(what) > 90 else ''} | **{status}** | "
                    f"{' · '.join(how).replace('|', '/')} |")

    L += ["## The 75 inventory rows", "",
          f"**{counts['fixed by rule']} fixed by rule, {counts['flagged by check']} flagged by check, "
          f"{len(uncovered)} not covered.**", "",
          "- **Fixed by rule:** the clean tables already correct it.",
          "- **Flagged by check:** the sources can't settle it, so it is kept and marked in the `issue` table. "
          "Take care with those records.", "",
          "| ID | Study | Impact | Problem (as the lab wrote it) | Status | How |", "|---|---|---|---|---|---|"] + rows + [""]
    OUT.write_text("\n".join(L))
    print(f"Coverage: {counts['fixed by rule']} fixed by rule, {counts['flagged by check']} flagged by check, "
          f"{len(uncovered)} not covered -> {OUT}")
    if uncovered:
        sys.exit(f"Inventory rows not covered: {uncovered}")


if __name__ == "__main__":
    main()
